# vim: set tabstop=4 softtabstop=4 shiftwidth=4 expandtab autoindent:

version: '2'

services:
    postgres:
        restart: always
        build: ./postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./django/webcode/media:/srv/webcode/media
        command: postgres

    django:
        restart: always
        build: ./django
        links:
            - postgres
        volumes:
            - /srv/workflows/static/
        volumes_from:
            - postgres
        ports:
            - 8000:8000
        command: /bin/bash -c "python manage.py makemigrations --noinput; python manage.py migrate --noinput; /usr/bin/uwsgi --emperor /etc/uwsgi/apps-enabled/openkgb.ini"

    nginx:
        restart: always
        build: ./nginx
        ports:
            - 80:80
            - 443:443
        depends_on:
            - django
        volumes_from:
            - django
            - postgres
        command: /bin/bash -c '/usr/sbin/nginx -g "daemon off;"'